server {
    listen 80;
    listen [::]:80;
    server_name sporty.samdpi.uz www.sporty.samdpi.uz;

    location = /favicon.ico {
        access_log off; log_not_found off;
    }
    location /static/ {
        root /root/sporty;
    }

    location /media/ {
        root /root/sporty;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/sporty.sock;
    }
}